apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Release.Name }}-django
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.secrets.djangoSecretKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
