{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  project: {{ .project }}
  source:
    repoURL: {{ .source.repoURL }}
    path: {{ .source.path }}
    targetRevision: {{ .source.targetRevision }}
    {{- with .source.helm }}
    helm:
      valueFiles:
        {{- range .valueFiles }}
        - {{ . }}
        {{- end }}
    {{- end }}
  destination:
    server: {{ .destination.server }}
    namespace: {{ .destination.namespace }}
  {{- with .syncPolicy }}
  syncPolicy:
    {{- with .automated }}
    automated:
      prune: {{ .prune }}
      selfHeal: {{ .selfHeal }}
    {{- end }}
  {{- end }}
---
{{- end }}
